### ISSUE TITLE
performance: optimise job progress tracking

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-workflow-engine-yadage#204]
Comparison of effectiveness of various workflow engines when talking to job controller for the RooFit example:

(1) Roofit CWL:

```
$ kubectl logs reana-run-batch-413a4712-08a8-4feb-873e-1e9747e1600a-bp5jp workflow-engine | wc -l
296
$ kubectl logs reana-run-batch-413a4712-08a8-4feb-873e-1e9747e1600a-bp5jp job-controller | wc -l
384
$ kubectl logs reana-run-batch-413a4712-08a8-4feb-873e-1e9747e1600a-bp5jp job-controller | grep werkz
2021-10-06 08:39:38,573 | werkzeug | MainThread | INFO |  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2021-10-06 08:39:47,814 | werkzeug | Thread-1 | INFO | 127.0.0.1 - - [06/Oct/2021 08:39:47] "GET /jobs HTTP/1.1" 200 -
2021-10-06 08:39:51,821 | werkzeug | Thread-2 | INFO | 127.0.0.1 - - [06/Oct/2021 08:39:51] "POST /jobs HTTP/1.1" 201 -
2021-10-06 08:39:51,826 | werkzeug | Thread-3 | INFO | 127.0.0.1 - - [06/Oct/2021 08:39:51] "GET /jobs/33d46567-d489-4a5a-9b74-47daa8414904 HTTP/1.1" 200 -
2021-10-06 08:39:56,835 | werkzeug | Thread-4 | INFO | 127.0.0.1 - - [06/Oct/2021 08:39:56] "GET /jobs/33d46567-d489-4a5a-9b74-47daa8414904 HTTP/1.1" 200 -
2021-10-06 08:39:57,886 | werkzeug | Thread-5 | INFO | 127.0.0.1 - - [06/Oct/2021 08:39:57] "POST /jobs HTTP/1.1" 201 -
2021-10-06 08:39:57,894 | werkzeug | Thread-6 | INFO | 127.0.0.1 - - [06/Oct/2021 08:39:57] "GET /jobs/a8c2525e-e922-4a3e-9a4b-c1c9f4dacb56 HTTP/1.1" 200 -
2021-10-06 08:40:02,903 | werkzeug | Thread-7 | INFO | 127.0.0.1 - - [06/Oct/2021 08:40:02] "GET /jobs/a8c2525e-e922-4a3e-9a4b-c1c9f4dacb56 HTTP/1.1" 200 -
```

(2) Roofit Serial:

```
$ kubectl logs reana-run-batch-0e439059-6141-4918-8c97-e571fee45678-wt2lh workflow-engine | wc -l
3
$ kubectl logs reana-run-batch-0e439059-6141-4918-8c97-e571fee45678-wt2lh job-controller | wc -l
390
$ kubectl logs reana-run-batch-0e439059-6141-4918-8c97-e571fee45678-wt2lh job-controller | grep werkz
2021-10-06 08:39:40,276 | werkzeug | MainThread | INFO |  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2021-10-06 08:39:49,420 | werkzeug | Thread-1 | INFO | 127.0.0.1 - - [06/Oct/2021 08:39:49] "GET /jobs HTTP/1.1" 200 -
2021-10-06 08:39:49,770 | werkzeug | Thread-2 | INFO | 127.0.0.1 - - [06/Oct/2021 08:39:49] "POST /jobs HTTP/1.1" 201 -
2021-10-06 08:39:49,774 | werkzeug | Thread-3 | INFO | 127.0.0.1 - - [06/Oct/2021 08:39:49] "GET /jobs/05fe18c4-924b-4506-88c1-176a2571968e HTTP/1.1" 200 -
2021-10-06 08:39:49,780 | werkzeug | Thread-4 | INFO | 127.0.0.1 - - [06/Oct/2021 08:39:49] "GET /jobs/05fe18c4-924b-4506-88c1-176a2571968e HTTP/1.1" 200 -
2021-10-06 08:39:52,788 | werkzeug | Thread-5 | INFO | 127.0.0.1 - - [06/Oct/2021 08:39:52] "GET /jobs/05fe18c4-924b-4506-88c1-176a2571968e HTTP/1.1" 200 -
2021-10-06 08:39:55,859 | werkzeug | Thread-6 | INFO | 127.0.0.1 - - [06/Oct/2021 08:39:55] "POST /jobs HTTP/1.1" 201 -
2021-10-06 08:39:55,862 | werkzeug | Thread-7 | INFO | 127.0.0.1 - - [06/Oct/2021 08:39:55] "GET /jobs/2a71e77b-23af-40fa-8f56-0fa810bd52d8 HTTP/1.1" 200 -
2021-10-06 08:39:55,865 | werkzeug | Thread-8 | INFO | 127.0.0.1 - - [06/Oct/2021 08:39:55] "GET /jobs/2a71e77b-23af-40fa-8f56-0fa810bd52d8 HTTP/1.1" 200 -
2021-10-06 08:39:58,872 | werkzeug | Thread-9 | INFO | 127.0.0.1 - - [06/Oct/2021 08:39:58] "GET /jobs/2a71e77b-23af-40fa-8f56-0fa810bd52d8 HTTP/1.1" 200 -
```

(3) RooFit Snakemake:

```
$ kubectl logs reana-run-batch-15c62147-5640-4c4b-8893-0cca208f9674-gr62d workflow-engine | wc -l
66
$ kubectl logs reana-run-batch-15c62147-5640-4c4b-8893-0cca208f9674-gr62d job-controller | wc -l
377
$ kubectl logs reana-run-batch-15c62147-5640-4c4b-8893-0cca208f9674-gr62d job-controller | grep werk
2021-10-06 08:39:44,236 | werkzeug | MainThread | INFO |  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2021-10-06 08:39:53,493 | werkzeug | Thread-1 | INFO | 127.0.0.1 - - [06/Oct/2021 08:39:53] "GET /jobs HTTP/1.1" 200 -
2021-10-06 08:39:53,900 | werkzeug | Thread-2 | INFO | 127.0.0.1 - - [06/Oct/2021 08:39:53] "POST /jobs HTTP/1.1" 201 -
2021-10-06 08:40:03,654 | werkzeug | Thread-3 | INFO | 127.0.0.1 - - [06/Oct/2021 08:40:03] "POST /jobs HTTP/1.1" 201 -
```

(4) RooFit Yadage:

```
$ kubectl logs reana-run-batch-4f715349-493b-47c0-8227-7a5b6801c3ed-5gfg5 workflow-engine | wc -l
447
$ kubectl logs reana-run-batch-4f715349-493b-47c0-8227-7a5b6801c3ed-5gfg5 job-controller | wc -l
377
$ kubectl logs reana-run-batch-4f715349-493b-47c0-8227-7a5b6801c3ed-5gfg5 job-controller | grep werkz
2021-10-06 08:39:42,332 | werkzeug | MainThread | INFO |  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2021-10-06 08:39:51,582 | werkzeug | Thread-1 | INFO | 127.0.0.1 - - [06/Oct/2021 08:39:51] "GET /jobs HTTP/1.1" 200 -
2021-10-06 08:39:57,645 | werkzeug | Thread-2 | INFO | 127.0.0.1 - - [06/Oct/2021 08:39:57] "POST /jobs HTTP/1.1" 201 -
2021-10-06 08:40:02,790 | werkzeug | Thread-3 | INFO | 127.0.0.1 - - [06/Oct/2021 08:40:02] "GET /jobs/bb0e2f4e-2143-444b-814b-01faad2dfbd5 HTTP/1.1" 200 -
2021-10-06 08:40:02,793 | werkzeug | Thread-4 | INFO | 127.0.0.1 - - [06/Oct/2021 08:40:02] "GET /jobs/bb0e2f4e-2143-444b-814b-01faad2dfbd5 HTTP/1.1" 200 -
2021-10-06 08:40:02,908 | werkzeug | Thread-5 | INFO | 127.0.0.1 - - [06/Oct/2021 08:40:02] "POST /jobs HTTP/1.1" 201 -
2021-10-06 08:40:08,057 | werkzeug | Thread-6 | INFO | 127.0.0.1 - - [06/Oct/2021 08:40:08] "GET /jobs/bb0e2f4e-2143-444b-814b-01faad2dfbd5 HTTP/1.1" 200 -
2021-10-06 08:40:08,059 | werkzeug | Thread-7 | INFO | 127.0.0.1 - - [06/Oct/2021 08:40:08] "GET /jobs/bb0e2f4e-2143-444b-814b-01faad2dfbd5 HTTP/1.1" 200 -
2021-10-06 08:40:08,098 | werkzeug | Thread-8 | INFO | 127.0.0.1 - - [06/Oct/2021 08:40:08] "GET /jobs/6d155a50-5000-4708-a552-d4fb1b64e426 HTTP/1.1" 200 -
2021-10-06 08:40:08,101 | werkzeug | Thread-9 | INFO | 127.0.0.1 - - [06/Oct/2021 08:40:08] "GET /jobs/6d155a50-5000-4708-a552-d4fb1b64e426 HTTP/1.1" 200 -
```

Note that the `bb0...` job status gets scanned four times. This is actually "gendata" step:

```
$ kubectl logs reana-run-batch-4f715349-493b-47c0-8227-7a5b6801c3ed-5gfg5 workflow-engine
...
              {
                    "metadata": {
                        "name": "gendata"
                    },
                    "id": "05aadc17-1d41-4ac6-88d5-b0a821749d4e",
                    "jobid": {
                        "job_id": "bb0e2f4e-2143-444b-814b-01faad2dfbd5"
                    }
                },
```

which is run first, so it looks like the workflow engine doesn't recall previous job statuses when it runs next steps and when those previous jobs are finished. This may lead to unnecessarily high job controller container work, which might be problem for more complex or for longer running workflows.

We should check for unnecessary tracking calls whilst the workflow is running and memoise all past job information, so that the job controller API wouldn't be unnecessarily hit so many times for the past "already-done, already-known" jobs.

To do:

- [x] reduce the amount of MQ messages from workflow-engine to `job-status` queue (#206)
- [x] reduce the number of API calls from workflow-engine to job-controller (#212)
- [ ] convert some `log.info` statements to `log.debug` to reduce amount of logs during normal operation

**Comment by lukasheinrich** [comment]
thee is a flag in yadage that controls the update frequency
https://github.com/reanahub/reana-workflow-engine-yadage/blob/master/reana_workflow_engine_yadage/cli.py#L65

what could also reduce the REST calls is if we can "batch query" multiple job ids

I need to check/remind mysslff if we can memoize the job result

**Comment by VMois** [comment]
Yadage tracker (`REANATracker`) is also sending a lot of duplicated status updates to the `job-status` message queue and this number is increasing with the running time of the workflows. Some benchmarks:

- 30 x atlas-demo-recast workflows produce **397** messages to the queue;
- 30 x atlas-demo-recast workflows + 5 min sleep (for a second step) produce **1734** messages

This amount of messages is causing `run-batch` jobs to be reported and cleaned much later after all `run-job` is finished. Those messages need to be processed unnecessarily by a **synchronous single-threaded** [job-status-consumer](https://github.com/reanahub/reana-workflow-controller/blob/7e7ccb2066547ad1f68dcf440b376d26c45dc5c4/reana_workflow_controller/consumer.py#L70) which make take a long-time.

We have started work on optimizing the Yadage engine.  We also plan to work on `job-status-consumer` improvements but this will be a separate issue.

**Comment by VMois** [comment]
There is a configuration in [reana-commons/config](https://github.com/reanahub/reana-commons/blob/86dd798259fbd7e5d4967a700243077fcc987012/reana_commons/config.py#L227) to get LOG_LEVEL. So it means the easiest way is to add it to the helm chart as an env variable.
